### ISSUE TITLE
ember-changeset hasMany relationship error

### ISSUE THREAD

**Issue by yusufsagdic** [poteto/ember-changeset#359]
Hi.

We are using latest version ember-changeset (2.1.2). We searched everywhere but we couldn't find the answer.

This code is not working and throws power-select-multiple.js:95 Uncaught TypeError: (select.selected || []).slice is not a function

      {{#form.element
        controlType="power-select-multiple"
        property="cities"
        placeholder="Select"
        label=(t "service_provider.cities")
        options=cities as |el|
      }}
        {{#el.control searchPlaceholder="Search..." as |item|}}
          {{item.name}}
        {{/el.control}}
      {{/form.element}}
If we change the code like this as he suggests everything is ok but this time changes doesn't apply to underlying object which changeset save doesn't send changed elements on serialized json.

      {{#form.element
        controlType="power-select-multiple"
        property="cities.content"
        placeholder="Select"
        label=(t "service_provider.cities")
        options=cities as |el|
      }}
        {{#el.control searchPlaceholder="Search..." as |item|}}
          {{item.name}}
        {{/el.control}}
      {{/form.element}}
I couldn't find any answer that ember-changeset has a support for hasMany relationship. Some says yes latest version does, some says doesn't or is this problem occuring because of power-select?

Is there any workaround to suggest?

Thanks.

**Comment by kitsuneyo** [comment]
I gave hasMany another go after upgrading to v2. This is what I have:

```
{{#form.element
      property="children"
      helpText=textContent.countries.help
      label=textContent.countries.label as |el|
    }}
      {{#power-select-multiple
        selected=el.value
        search=(action "searchCountries")
        placeholder=textContent.countries.placeholder
        onchange=(action (mut el.value)) as |option|
      }}
        <span>{{option.name}}</span>
      {{/power-select-multiple}}
    {{/form.element}}
```

It appears to work and changes persist in Ember Data (I think), but on refreshing the page changes disappear as they are not sent to the back-end.

The problem could be Ember-Bootstrap-related?

For now I am putting my hasMany relationships on separate, non-changeset forms.

**Comment by yusufsagdic** [comment]
@kitsuneyo thanks for reply.

Your example for create form but I have problem with update.My property is _**services**_ 
and I find a solution like this. 
I set changeset.services.content for show selected and set changeset.services for post data.

**Controller**
`    
  services: computed(function () {
    return this.store.findAll('service');
  }),
  actions: {
updateServices(option) {
      let changeset = this.get('changeset');
      changeset.set('services.content', option);
      changeset.set('services', option);
    }
  }`

**Template**
` {{#power-select-multiple
          selected=changeset.services.content
          options=services
          placeholder="Search..."
          onchange=(action "updateServices") as |option|
        }}
        {{option.name}}
      {{/power-select-multiple}}`

**Comment by kitsuneyo** [comment]
@yusufsagdic 

My example works for both create and update.

I notice your solution requires a standalone action `updateServices`. I have had to do that in the past, and I think the problem was with how Ember-Bootstrap and Power Select work together, rather than Changeset.

With the latest versions of the add-ons I'm finding I don't need to write those separate actions as often. Which versions are you on? I have:

- Ember 3.10
- Ember Changeset 2.1.2
- Ember Bootstrap 2.8.0
- Ember Power Select 2.3.5
