### ISSUE TITLE
1.4.2-beta-1 causes several errors related to ember.get vs changeset.get

### ISSUE THREAD

**Issue by danwenzel** [poteto/ember-changeset#289]
## Version 1.4.2-beta-1 (depended on by `ember-changeset-validations@1.2.11`

When upgrading `ember-changeset-validations` to 1.2.11, we are experiencing several errors when trying to get properties of changesets.

We get errors in js files like: `startDateTime.format is not a function`

We also get errors when referencing sub-properties of changesets in templates.  For example:

```
{{some-component events=changeset.timeline.events}}
```

...gives an error: `Uncaught Error: Assertion Failed: content must be present.`

It appears that this is related to a recent change now referenced in the README, where it is suggested to use `changeset.get`, not `Ember.get`: https://github.com/poteto/ember-changeset#get

However, all of these instances of using `Ember.get` were working just fine before, so this seems like either a bug or a breaking change to me.  It would be extremely time-consuming to have to replace all instances of `Ember.get` with `changeset.get` in our codebase, especially considering templates are affected too (see above).  Even if we did, the code now looks a lot more verbose than it did before.  Couldn't we figure out a way to just get Ember.get to work like it did before?

Thanks, and let me know if you need any more information.

**Comment by mukk85** [comment]
Looks like the same issue as #281

**Comment by nucleartide** [comment]
@danwenzel Thanks for the report - you’ve raised some usability issues I hadn’t considered. The primary reason why the docs suggest `changeset.get` is to hide some of the implementation details for nested keys. Since it is a _beta_ release, some bugs are to be expected.

I would go back and use the 1.3.x versions of ember-changeset for now. And if you have any suggestions for how to fix this, please post them here or open a PR. (Since I only have so much time to work on this lib.)

**Comment by danwenzel** [comment]
Thanks, @nucleartide . Our issue stemmed from the fact that the latest `ember-changeset-validations` depends on this beta version.  I just filed an issue over there.

**Comment by mukk85** [comment]
@danwenzel Per the comment in 218, if you are using yarn add the following to your package.json and it will load a version without this bug.

`"resolutions":` {
	"ember-changeset-validations/**/ember-changeset": "1.4.1"
}`

**Comment by nucleartide** [comment]
I would also use `1.3.0`, since `1.4.1` has a few bugs as well.

**Comment by snewcomer** [comment]
Just for documentation purposes, this proxy implementation (due to nested keys support) has created many a problems.  Sometime in October, I plan on refactoring this out.

#317

**Comment by snewcomer** [comment]
Just to notify everyone, `2.0.0-beta.0` has been published for ember-changeset and ember-changeset-validations.  Give it a shot!  @danwenzel

**Comment by danwenzel** [comment]
I no longer have a way to test this, but I'm guessing it's probably fine.
